"use client";

import { use, useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { getUser, fetchUserMe } from "@/lib/auth";
import { api } from "@/lib/api";
import { canUse, type Tier } from "@/lib/tiers";
import PlanView from "@/components/PlanView";
import NutritionPanel, { type NutritionData } from "@/components/NutritionPanel";
import PeriodizationBar, { type PeriodWeek } from "@/components/PeriodizationBar";
import TierGate from "@/components/TierGate";
import { normalizeWeeks } from "@/lib/normalizeWeeks";

interface PlanDetail {
  id: string;
  tier_at_creation: string;
  profile_snapshot: Record<string, unknown>;
  mesocycle_weeks: number;
  current_week: number;
  phase: string;
  plan_data: Record<string, unknown>;
  nutrition: Record<string, unknown>;
  persona_used: string;
  created_at: string;
  is_active: boolean;
}



function normalizeNutrition(raw: Record<string, unknown>): NutritionData {
  return {
    daily_calories:
      typeof raw.daily_calories === "number" ? raw.daily_calories : undefined,
    training_day:
      raw.training_day && typeof raw.training_day === "object"
        ? (raw.training_day as NutritionData["training_day"])
        : undefined,
    rest_day:
      raw.rest_day && typeof raw.rest_day === "object"
        ? (raw.rest_day as NutritionData["rest_day"])
        : undefined,
    notes: typeof raw.notes === "string" ? raw.notes : undefined,
  };
}

// --- Tier badge ---

const TIER_BADGE_STYLES: Record<string, string> = {
  free: "bg-zinc-700 text-zinc-200",
  pro: "bg-blue-600 text-white",
  elite: "bg-amber-600 text-white",
};

function TierBadge({
  tier,
  personaUsed,
}: {
  tier: string;
  personaUsed: string;
}) {
  const style = TIER_BADGE_STYLES[tier] ?? TIER_BADGE_STYLES.free;

  return (
    <div className={`${style} rounded-lg px-4 py-2.5 text-sm font-medium`}>
      Generated by {personaUsed}
    </div>
  );
}

// --- Page ---

export default function PlanPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();
  const [plan, setPlan] = useState<PlanDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selectedWeek, setSelectedWeek] = useState(1);
  const [userTier, setUserTier] = useState<Tier>("free");
  const [confirming, setConfirming] = useState(false);
  const [discarding, setDiscarding] = useState(false);
  const slideDirection = useRef<"left" | "right">("right");

  function handleWeekSelect(week: number) {
    slideDirection.current = week > selectedWeek ? "left" : "right";
    setSelectedWeek(week);
  }

  useEffect(() => {
    const user = getUser();
    if (!user) {
      router.push("/");
      return;
    }

    async function fetchPlan() {
      try {
        // Fetch tier from server (not JWT) to prevent client-side tier spoofing
        const me = await fetchUserMe();
        if (me) setUserTier(me.tier as Tier);

        const data = await api<PlanDetail>(`/plan/${id}`);
        setPlan(data);
        setSelectedWeek(data.current_week);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to load plan."
        );
      } finally {
        setLoading(false);
      }
    }

    fetchPlan();
  }, [id, router]);

  async function handleConfirm() {
    setConfirming(true);
    try {
      await api(`/plan/${id}/confirm`, { method: "POST" });
      setPlan((prev) => (prev ? { ...prev, is_active: true } : prev));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to confirm plan.");
    } finally {
      setConfirming(false);
    }
  }

  async function handleRegenerate() {
    setDiscarding(true);
    try {
      await api(`/plan/${id}`, { method: "DELETE" });
      router.push("/plan/loading");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to discard plan.");
      setDiscarding(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-zinc-950 flex items-center justify-center">
        <div className="w-8 h-8 rounded-full border-2 border-zinc-700 border-t-blue-500 animate-spin" />
      </div>
    );
  }

  if (error || !plan) {
    return (
      <div className="min-h-screen bg-zinc-950 flex items-center justify-center p-4">
        <div className="text-center max-w-sm">
          <p className="text-red-400 font-medium mb-4">
            {error || "Plan not found."}
          </p>
          <a
            href="/"
            className="text-blue-400 hover:text-blue-300 text-sm transition-colors"
          >
            Back to home &rarr;
          </a>
        </div>
      </div>
    );
  }

  const tier = plan.tier_at_creation as Tier;
  const weeks = normalizeWeeks(plan.plan_data);
  const nutrition = normalizeNutrition(plan.nutrition);
  const currentWeekData = weeks.find(
    (w) => w.week_number === selectedWeek
  ) ?? weeks[selectedWeek - 1] ?? null;

  const competitionDate =
    plan.profile_snapshot?.competition_date as string | null | undefined;

  // Extract rationale if present
  const rationale =
    typeof plan.plan_data.rationale === "string"
      ? plan.plan_data.rationale
      : null;

  return (
    <div className="min-h-screen bg-zinc-950 text-white pb-20">
      <div className="max-w-2xl mx-auto px-4 py-6 space-y-4">
        {/* Tier badge */}
        <TierBadge tier={tier} personaUsed={plan.persona_used ?? "Coach"} />

        {!plan.is_active && (
          <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-4 space-y-3">
            <div className="flex items-center gap-2">
              <span className="text-amber-500 text-xs bg-amber-900/30 px-2 py-0.5 rounded-full font-medium">
                Preview
              </span>
              <span className="text-zinc-400 text-sm">Review before activating</span>
            </div>
            <p className="text-zinc-400 text-sm">
              This is a preview of your new plan. Activate it to start training,
              or generate a different one.
            </p>
            <div className="flex gap-3">
              <button
                onClick={handleConfirm}
                disabled={confirming || discarding}
                className="flex-1 py-3 bg-green-600 hover:bg-green-500 disabled:bg-zinc-700 disabled:text-zinc-400 rounded-xl font-medium text-white transition-colors"
              >
                {confirming ? "Activating..." : "Activate This Plan"}
              </button>
              <button
                onClick={handleRegenerate}
                disabled={confirming || discarding}
                className="flex-1 py-3 bg-zinc-800 hover:bg-zinc-700 disabled:bg-zinc-700 disabled:text-zinc-400 border border-zinc-600 rounded-xl font-medium text-zinc-200 transition-colors"
              >
                {discarding ? "Discarding..." : "Generate New Plan"}
              </button>
            </div>
          </div>
        )}

        {tier === "free" && (
          <p className="text-zinc-500 text-xs">
            Upgrade to Pro for evidence-based research and longer mesocycles.{" "}
            <a
              href="/settings"
              className="text-blue-400 hover:text-blue-300 transition-colors"
            >
              Learn more
            </a>
          </p>
        )}

        {/* Periodization bar */}
        {weeks.length > 0 && (
          <PeriodizationBar
            weeks={weeks}
            currentWeek={plan.current_week}
            selectedWeek={selectedWeek}
            onWeekSelect={handleWeekSelect}
            tier={tier}
            competitionDate={competitionDate}
          />
        )}

        {/* Rationale (pro/elite) */}
        {rationale && canUse(tier, "web_search") && (
          <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-4">
            <p className="text-zinc-400 text-sm">{rationale}</p>
          </div>
        )}

        {/* Week heading + Plan view with slide animation */}
        {currentWeekData ? (
          <div
            key={selectedWeek}
            className="space-y-4"
            style={{
              animation: `${slideDirection.current === "left" ? "slideInFromRight" : "slideInFromLeft"} 200ms ease-out`,
            }}
          >
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">
                Week {selectedWeek}
                {currentWeekData.phase && (
                  <span className="text-zinc-400 font-normal text-sm ml-2">
                    {currentWeekData.phase.replace(/[_-]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}
                  </span>
                )}
              </h2>
            </div>
            <PlanView week={currentWeekData} tier={tier} />
          </div>
        ) : weeks.length > 0 ? (
          <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-6 text-center">
            <p className="text-zinc-400">
              Select a week above to view your training plan.
            </p>
          </div>
        ) : (
          <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-6 text-center">
            <p className="text-zinc-400">
              No training data available for this plan.
            </p>
          </div>
        )}

        {/* TierGate: adaptation (free → pro) */}
        <TierGate
          feature="adaptation"
          currentTier={userTier}
          title="Weekly AI Adaptation"
          description="Get personalized adjustments based on your weekly check-ins and recovery data."
          requiredTier="pro"
        />

        {/* Nutrition panel */}
        <NutritionPanel nutrition={nutrition} tier={tier} />

        {/* TierGate: coach chat (free/pro → elite) */}
        <TierGate
          feature="coach_chat"
          currentTier={userTier}
          title="Coach Chat"
          description="Chat directly with your AI coach for real-time training advice and program adjustments."
          requiredTier="elite"
        />

        {/* Footer */}
        <div className="pt-4 border-t border-zinc-800 flex items-center justify-between text-sm">
          <span className="text-zinc-500">
            Created{" "}
            {new Date(plan.created_at).toLocaleDateString(undefined, {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="text-zinc-500 hover:text-white text-xs transition-colors no-print"
              title="Print / export plan"
            >
              Export
            </button>
            {plan.is_active && (
              <span className="text-green-500 text-xs bg-green-900/30 px-2 py-0.5 rounded-full">
                Active
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
